### ISSUE TITLE
Print view shows irrelevant elements

### ISSUE THREAD

**Issue by schneidr** [nextcloud/cookbook#1945]
**Description**
The latest additions for calculations of portions also show up on the print view.

**Reproduction**
1. Open a recipe where not all ingredients have a calculable amount
2. Open the print dialog

**Actual behavior**
The `Copy ingredients` button, the error icon in the ingredient line and the error message below show up on the print view.

**Expected behavior**
These elements should not be visible in the print view, as they are irrelevant for a printed recipe

**Screenshots**
![nextcloud_cookbok_print](https://github.com/nextcloud/cookbook/assets/401729/c088133c-f229-41eb-8da0-089e38d1977e)

**Browser**
Firefox 120, Chrome 120, the browser is irrelevant.

**Versions**
Nextcloud server version: 27.1.4
Cookbook version: 0.10.4
Database system: MySQL

**Comment by schneidr** [comment]
Example CSS to hide these elements:

```css
@media print {
  section.ingredients button.copy-ingredients,
  section.ingredients span.icon-error,
  .ingredient-parsing-error {
    display: none;
  }
}
```
